/**
 * Generates the data snapshots for the "Code Explorer" example (examples/code-explorer):
 *
 *   src/data/vlist-tree.js     — vlist source as a flat tree (dir → file → symbol)
 *   src/data/vlist-history.js  — vlist git history (one entry per commit, with
 *                                the src/ files it touched, for per-file history)
 *
 * Deploy-safe: the snapshots are committed, so the example never needs the vlist
 * git repo at build/deploy time. Re-run locally when you want to refresh them:
 *
 *   bun scripts/gen-code-explorer-data.ts
 *
 * The vlist repo is resolved relatively (sibling checkout, per the `file:../vlist`
 * dev layout) or via the VLIST_REPO env var — never an absolute path.
 */

import { readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";

const REPO = process.env.VLIST_REPO ?? resolve(import.meta.dir, "../../vlist");
const DATA_DIR = resolve(import.meta.dir, "../src/data");
const HEADER =
  "// AUTO-GENERATED by scripts/gen-inspector-data.ts — do not edit by hand.\n" +
  "// Refresh: bun scripts/gen-inspector-data.ts\n";

// =============================================================================
// Code tree — exported symbols across src/**/*.ts, as flat parentId nodes
// =============================================================================

type Node = {
  id: string;
  parentId: string | null;
  name: string;
  kind: string;
  signature?: string;
  module?: string;
  exported?: boolean;
};

// Match top-level declarations — exported or not. The `^` anchor with `m` flag
// ensures we only match lines at column 0 (no leading whitespace), which
// excludes nested variables/functions inside function bodies.
const DECL_RE =
  /^(?:export\s+)?(?:declare\s+)?(?:abstract\s+)?(?:async\s+)?(function|const|let|var|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/gm;

function buildTree(): Node[] {
  const files = [...new Bun.Glob("src/**/*.ts").scanSync({ cwd: REPO })]
    .filter((f) => !f.endsWith(".d.ts"))
    .sort();

  const nodes: Node[] = [];
  const dirSeen = new Set<string>();

  const ensureDir = (dir: string): string | null => {
    if (!dir) return null;
    if (!dirSeen.has(dir)) {
      const slash = dir.lastIndexOf("/");
      const parent = slash >= 0 ? dir.slice(0, slash) : "";
      const parentId = parent ? ensureDir(parent) : null;
      dirSeen.add(dir);
      nodes.push({ id: dir, parentId, name: dir.split("/").pop()!, kind: "dir" });
    }
    return dir;
  };

  for (const file of files) {
    const dir = file.slice(0, file.lastIndexOf("/"));
    ensureDir(dir);
    nodes.push({ id: file, parentId: dir, name: file.split("/").pop()!, kind: "file" });

    const src = readFileSync(join(REPO, file), "utf8");
    const seen = new Set<string>();
    let m: RegExpExecArray | null;
    DECL_RE.lastIndex = 0;
    while ((m = DECL_RE.exec(src)) !== null) {
      const rawKind = m[1]!;
      const name = m[2]!;
      if (seen.has(name)) continue;
      seen.add(name);
      // Extract the signature: start from the match (not lineStart — avoids
      // preceding comments), read until brackets balance and we hit `{`, `;`,
      // or `=` at depth 0.
      let depth = 0;
      let sigEnd = m.index;
      for (let i = m.index; i < src.length; i++) {
        const ch = src[i]!;
        if (ch === "(" || ch === "<") depth++;
        else if ((ch === ")" || ch === ">") && depth > 0) depth--;
        else if (depth === 0 && (ch === "{" || ch === ";" || ch === "=")) {
          sigEnd = i;
          break;
        }
        sigEnd = i + 1;
      }
      const signature = src
        .slice(m.index, sigEnd)
        .trim()
        .replace(/\s+/g, " ")
        .replace(/\s*\{?\s*$/, "");
      const kind = rawKind === "let" || rawKind === "var" ? "const" : rawKind;
      const exported = signature.startsWith("export");
      nodes.push({ id: `${file}#${name}`, parentId: file, name, kind, signature, module: file, exported });
    }

    // Capture re-exports: `export { X, Y } from "./Z"` and `export type { X } from "./Z"`
    const REEXPORT_RE = /^export\s+(?:type\s+)?\{([^}]+)\}\s+from\s+["']([^"']+)["']/gm;
    let re: RegExpExecArray | null;
    while ((re = REEXPORT_RE.exec(src)) !== null) {
      const names = re[1]!.split(",").map((s) => s.trim().split(/\s+as\s+/).pop()!.trim()).filter(Boolean);
      const from = re[2]!;
      const isType = re[0]!.startsWith("export type");
      for (const n of names) {
        if (seen.has(n)) continue;
        seen.add(n);
        const kind = isType ? "type" : "re-export";
        nodes.push({
          id: `${file}#${n}`,
          parentId: file,
          name: n,
          kind,
          signature: `export { ${n} } from "${from}"`,
          module: file,
          exported: true,
        });
      }
    }
  }
  return nodes;
}

// =============================================================================
// History — one entry per commit
// =============================================================================

type Commit = {
  id: string;
  hash: string;
  shortHash: string;
  author: string;
  date: string;
  subject: string;
  type: string;
  tag?: string;
  /** Changed files under src/ — drives per-file history. */
  files: string[];
};

const CC_TYPES = new Set([
  "feat", "fix", "docs", "style", "refactor", "perf", "test", "chore", "build", "ci", "revert",
]);

function buildTagMap(): Map<string, string> {
  const out = Bun.spawnSync(
    ["git", "-C", REPO, "tag", "-l", "--format=%(objectname) %(refname:short)"],
    { stdout: "pipe" },
  ).stdout.toString();
  const map = new Map<string, string>();
  for (const line of out.split("\n")) {
    const [hash, tag] = line.trim().split(" ");
    if (hash && tag) map.set(hash, tag);
  }
  return map;
}

function buildHistory(): Commit[] {
  const tags = buildTagMap();

  // Unit-separated header line per commit, then one changed-file path per line.
  const fmt = "%x1e%H%x1f%h%x1f%an%x1f%ad%x1f%s";
  const out = Bun.spawnSync(
    ["git", "-C", REPO, "log", "--name-only", `--pretty=format:${fmt}`, "--date=short"],
    { stdout: "pipe" },
  ).stdout.toString();

  const commits: Commit[] = [];
  for (const record of out.split("\x1e")) {
    if (!record.trim()) continue;
    const [header, ...rest] = record.split("\n");
    const [hash, shortHash, author, date, subject] = header!.split("\x1f");
    const files = rest
      .map((l) => l.trim())
      .filter((l) => l.startsWith("src/"));
    const tm = /^(\w+)(?:\([^)]*\))?!?:/.exec(subject ?? "");
    const type = tm && CC_TYPES.has(tm[1]!) ? tm[1]! : "other";
    const commit: Commit = {
      id: shortHash!,
      hash: hash!,
      shortHash: shortHash!,
      author: author!,
      date: date!,
      subject: subject ?? "",
      type,
      files,
    };
    const tag = tags.get(hash!);
    if (tag) commit.tag = tag;
    commits.push(commit);
  }
  return commits;
}

// =============================================================================
// Write
// =============================================================================

const tree = buildTree();
const history = buildHistory();

writeFileSync(
  join(DATA_DIR, "vlist-tree.js"),
  `${HEADER}export const VLIST_TREE = ${JSON.stringify(tree)};\n`,
);
writeFileSync(
  join(DATA_DIR, "vlist-history.js"),
  `${HEADER}export const VLIST_HISTORY = ${JSON.stringify(history)};\n`,
);

const symbols = tree.filter((n) => n.kind !== "dir" && n.kind !== "file").length;
const files = tree.filter((n) => n.kind === "file").length;
const dirs = tree.filter((n) => n.kind === "dir").length;
console.log(`vlist-tree.js    → ${tree.length} nodes (${dirs} dirs, ${files} files, ${symbols} symbols)`);
console.log(`vlist-history.js → ${history.length} commits`);
